name: mister-pokeylope
url: http://misterpokeylope.github.io
markdown: redcarpet
permalink: pretty
highlighter: pygments 
excerpt_separator: <!--more-->
paginate: 5 
paginate_path: "/page:num"
gems:
- jekyll-sitemap
