name: mister-pokeylope
url: http://www.misterpokeylope.com
markdown: redcarpet
permalink: pretty
highlighter: rouge 
excerpt_separator: <!--more-->
paginate: 5 
paginate_path: "/page:num"
gems:
- jekyll-sitemap
